# Platform configuration helper

function(detect_platform)
    if(WIN32)
        set(PLATFORM_NAME "Windows" PARENT_SCOPE)
        set(PLATFORM_WINDOWS ON PARENT_SCOPE)
    elseif(APPLE)
        if(IOS)
            set(PLATFORM_NAME "iOS" PARENT_SCOPE)
            set(PLATFORM_IOS ON PARENT_SCOPE)
        else()
            set(PLATFORM_NAME "macOS" PARENT_SCOPE)
            set(PLATFORM_MACOS ON PARENT_SCOPE)
        endif()
    elseif(ANDROID)
        set(PLATFORM_NAME "Android" PARENT_SCOPE)
        set(PLATFORM_ANDROID ON PARENT_SCOPE)
    elseif(UNIX)
        set(PLATFORM_NAME "Linux" PARENT_SCOPE)
        set(PLATFORM_LINUX ON PARENT_SCOPE)
    else()
        set(PLATFORM_NAME "Unknown" PARENT_SCOPE)
    endif()
endfunction()

detect_platform()
